### ISSUE TITLE
Authentication Password, Model and Table in config.php

### ISSUE THREAD

**Issue by rfiedler** [XavRsl/Cas#10]
Hi! I have installed the CAS in my laravel 4.2. In the configuration file see commented notes referring to (array key's) password authentication, Model and Table but these "key's array" are not present in the configuration file. You can send me the text of these "keys array" ..... something like "cas_password" , "cas_model" or "cas_table"  .....

**Comment by rfiedler** [comment]
Sorry, I'll try to explain in more detail. CAS package configuration file (config.php) There commented lines explaining each key of the array. 
For example, at the beginning of the config file have "PHPCas Hostname" refers to the key 'cas_hostname' => 'cas.domain.fr', 
but comments 
Authentication PasswordAuthentication ModelAuthentication Table
They are not referring to any key in config file...... 

For Example:
Authentication Password to "cas_password"=>'mypassword'

What are the keys to model, table and password? Where the specific model, table and passoword?

Thanks 
Date: Wed, 7 Jan 2015 05:05:55 -0800

**Comment by XavRsl** [comment]
Sorry mate,
In fact, those comments are rubbish. Sorry. They're actually just remaining elements from the config file that I've been using as a starting point when I developed the package. They must go.

Xavier
