### ISSUE TITLE
compatibility with Laravel 5

### ISSUE THREAD

**Issue by robertobarbiera** [XavRsl/Cas#14]
Hi! Any roadmap to have the version working with L5?

**Comment by XavRsl** [comment]
I'm working on it... I think it will work as a middleware so I need to
rewrite most of it. I'll try to publish development branch rapidly.

Xavier

2015-02-08 17:07 GMT+01:00 robertobarbiera <notifications@github.com>:

> Hi! Any roadmap to have the version working with L5?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/XavRsl/Cas/issues/14>.
>



-- 
Xavier

**Comment by peyobr** [comment]
Well,

we are looking forward to try it!

**Comment by XavRsl** [comment]
Be my guest !
Version 1.2.* works on Laravel 5. It's a very simple version, I got rid of
a few elements such as auth and session objects used when logout. I didn't
want to deal with the Laravel Session an the Laravel Auth systems in my
plugin as it was made in earlier versions. So if you need to end a session
and logout from Laravel's Auth, do it before using Cas's logout and
everything should be fine.

Xavier

2015-02-27 11:08 GMT+01:00 peyobr <notifications@github.com>:

> Well,
>
> we are looking forward to try it!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/XavRsl/Cas/issues/14#issuecomment-76368734>.
>



-- 
Xavier

**Comment by peyobr** [comment]
This simply works for me. It's up to me handling the logout.

Thank you!

Route::filter('cas', function(){
	
	Cas::authenticate();
	
	Auth::login(User::where('username', Cas::getCurrentUser())->first());
	
});

Route::group(['before' => 'cas'], function(){

	Route::resource('nets', 'NetsController');

});

**Comment by XavRsl** [comment]
It handles the logout but probably doesn't kill the session. Although it
should as Cas itself renames the SESSIONID to one that it is able to kill...
I have to make more tests...

Xavier

2015-02-27 16:18 GMT+01:00 peyobr <notifications@github.com>:

> This simply works for me. It's up to me handling the logout.
>
> Thank you!
>
> Route::filter('cas', function(){
>
> Cas::authenticate();
>
> Auth::login(User::where('username', Cas::getCurrentUser())->first());
>
> });
>
> Route::group(['before' => 'cas'], function(){
>
> Route::resource('nets', 'NetsController');
>
> });
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/XavRsl/Cas/issues/14#issuecomment-76410181>.
>



-- 
Xavier
