### ISSUE TITLE
Add support for custom session cookie names

### ISSUE THREAD

**Issue by subfission** [XavRsl/Cas#20]
Is it possible to store the session data, entirely withing laravel sessions OR adjust the cookie name from default?

**Comment by jondmcelroy** [comment]
I would love for someone to rework this to store the session data in the laravel session, since I am having many issues with a CAS login against a load balancer server with laravel and phpCAS.

**Comment by subfission** [comment]
@jondmcelroy I have my own customized variant of this plugin.  You are welcome to give it a shot if you need that functionality.
