### ISSUE TITLE
Too many redirects problem

### ISSUE THREAD

**Issue by wangyi717** [XavRsl/Cas#23]
Hi, I stuck in with the trouble of "ERR_TOO_MANY_REDIRECTS". When I type an url in Chrome, the browser show me this message. I don't know how to deal with it. I write "Cas::authenticate" in the constructor of the controller, is this right? Could you please give me some examples to show how to use the Cas correctly? THX and forgive my poor English.

**Comment by XavRsl** [comment]
Hello,
You could put your Cas::authenticate() call in a filter called before your controller, or in a middleware if you're using Laravel 5. Anyway, your problem could also come from your CAS setup, having nothing to do with this plugin. What version of the plugin are you using ? What version of CAS server are you using ? Is your application allowed to use the CAS server ? 

Xavier

**Comment by wangyi717** [comment]
I've solved this problem. I lost "$" of "$query_string" in my nginx.conf, so phpCAS can't read the ticket in the URI. Anyway, thanks a lot.

**Comment by XavRsl** [comment]
Ok. That's the problem with CAS. It involves a lot more than just a plugin
which makes it really complex.

See you
