### ISSUE TITLE
How do you append the service when loging out a user

### ISSUE THREAD

**Issue by demonmind** [XavRsl/Cas#31]
I call Cas::logout() and the users logs out but the url of the SSO server does not have the service parameter with it. How do i add the service url to logout so the url becomes the same as when i login?

**Comment by XavRsl** [comment]
Here's an example :
```
Cas::logout(['service' => url('/')]);
```

**Comment by demonmind** [comment]
I get this error

phpCAS error: phpCAS::logoutWithRedirectService(): type mismatched for parameter $service (should be `string')

**Comment by demonmind** [comment]
This worked Cas::logout(url('/'));

Thanks

**Comment by XavRsl** [comment]
:+1:

**Comment by demonmind** [comment]
@XavRsl is there a way i can create user if the user is not found in the local app, but it is found in the cas-server?

I am referring to something like this:

https://github.com/Fnatte/laravel-cas/blob/master/src/Teuz/LaravelCas/Cas.php#L159

**Comment by XavRsl** [comment]
I put this in a Middleware like that :
```
public function handle($request, Closure $next)
    {
        Cas::authenticate();

        if (!Auth::check()) {
            Auth::login(
                CasUser::register(Cas::user())
            );
        }

        return $next($request);
    }
```
And my CasUser class looks like :
```
class CasUser
{

    public static function register($login)
    {
        if ($user = User::where('login', $login)->first())
        {
            return $user;
        }

        return User::create([
            'login' => $login,
            'name' => Ldap::people($login)->displayname,
            'email' => Ldap::people($login)->mail
        ]);
    }
}
```
