### ISSUE TITLE
Update to phpCAS 1.3.4

### ISSUE THREAD

**Issue by paszczus** [XavRsl/Cas#34]
It would be nice if you could update phpCAS to newer version please.

**Comment by XavRsl** [comment]
Hi !
Yes, the change is already there but I didn't make a release for it... 
I'll do that quickly.

Xavier

**Comment by XavRsl** [comment]
Done ! https://github.com/XavRsl/Cas/releases/latest

**Comment by paszczus** [comment]
Thank you!
