### ISSUE TITLE
checkAuthenticate() need to return value

### ISSUE THREAD

**Issue by wu-yuanhui** [XavRsl/Cas#43]
Hello, my english is very pool, please understand.

In Cas/src/Xavrsl/Cas/Sso.php near line 161, there is a method named checkAuthenticate(),
it call the phpCAS::checkAuthentication() method, and the phpCAS::checkAuthentication() will return true or false. So, i think Sso need to return the value too. Like this:

···php

    public function checkAuthenticate()
    {
        if($this->isPretending()) return true;
        try
        {
            // phpCAS::checkAuthentication();                        <====this line need to return value.
            return phpCAS::checkAuthentication();
        }
        catch(\Exception $e)
        {
            throw new CasAuthenticationException;
        }
    }
```

Please fix it as soon as possible, thinks, thinks, thinks.

**Comment by XavRsl** [comment]
I haven't used that package for a while and it's not really maintained anymore... I encourage you to use https://github.com/subfission/cas instead as it is originally a fork of my package but maintained.

Sorry.

Xavier
