### ISSUE TITLE
Custom Event / Exception Handling if there is authentication error.

### ISSUE THREAD

**Issue by sadhakbj** [XavRsl/Cas#44]
- I am using this package in my web application and for CAS I am using apereo.github.io/cas , I need custom event handling / exception handling in case of authentication failure. Is that possible through this package or I need to make changes on my Java CAS system ?

**Comment by XavRsl** [comment]
You could probably fork this repo and make your own event handler. I don't know if Apereo CAS provides any way to extend its lib to fire events.
