### ISSUE TITLE
cas()->getCurrentUser()

### ISSUE THREAD

**Issue by soufianekhait** [XavRsl/Cas#47]
Hey, I'm having an issue getting the current user through the CAS server.
I can't get the username using **cas()->getCurrentUser()**, it returns 

> Error: Internal script failure

Here's some screenshots of my **cas.php** : 

![1](https://user-images.githubusercontent.com/45060816/50825682-e9516500-1339-11e9-9a4a-d887b1e8f248.PNG)
![2](https://user-images.githubusercontent.com/45060816/50825693-f0787300-1339-11e9-8123-a067bf373780.PNG)
![3](https://user-images.githubusercontent.com/45060816/50825694-f0787300-1339-11e9-87ed-f1af9911d408.PNG)
![4](https://user-images.githubusercontent.com/45060816/50825695-f1110980-1339-11e9-982a-93b98976f97c.PNG)
![5](https://user-images.githubusercontent.com/45060816/50825702-f4a49080-1339-11e9-95fa-70a44161ded2.PNG)

Fortunately, I can connect to the server and generate a ticket but I can't get the username : 

![capture](https://user-images.githubusercontent.com/45060816/50825894-84e2d580-133a-11e9-83c0-5cc54b9f8c32.PNG)

![222](https://user-images.githubusercontent.com/45060816/50825948-a643c180-133a-11e9-8e42-778281dbfec2.PNG)

**Comment by XavRsl** [comment]
Hi,
From what I can see, you're actually using another CAS plugin for your applications. Maybe you should post your issue on the other CAS plugin's repo?
Here you go: https://github.com/subfission/cas/issues
