### ISSUE TITLE
Laravel 6 support

### ISSUE THREAD

**Issue by brunogoossens** [XavRsl/Cas#48]
This package blocks a Laravel 5.8 to Laravel 6 update because  xavrsl/cas v1.2.6 requires illuminate/support 4.*|5.* .

**Comment by XavRsl** [comment]
Hi Bruno,

Thanks for your interest in this package but I don't maintain it anymore. You should have a look at this replacement package: https://github.com/subfission/cas

Thanks.

Xavier
