### ISSUE TITLE
Not working with Laravel 8.*

### ISSUE THREAD

**Issue by MFranklinJ** [XavRsl/Cas#52]
Hi,

It is working well in Laravel 5.2. When I upgraded to 8.* it is not working. I want to know whether it is compatible with Laravel 8.* or not. If yes, what are the changes to be done?

**Comment by XavRsl** [comment]
Hi Bruno,

Thanks for your interest in this package but I don't maintain it anymore. You should have a look at this replacement package: https://github.com/subfission/cas

Thanks.

Xavier
